### ISSUE TITLE
Dividir e implementar el modelo de datos en SQL y NoSQL

### ISSUE THREAD

**Issue by SaintChoppa** [ISCOUTB/AH-CineManager#2]

**Comment by SaintChoppa** [comment]
Ya se realizó el modelo entidad relación, pero falta por la normalización del mismo, cuando se realice se subirá al momento

**Comment by SaintChoppa** [comment]
![Image](https://github.com/user-attachments/assets/476a1b3c-6d4c-4ac5-bf90-e8ac608271af)

Primera parte del modelo de datos en SQL, faltan la descripción de los datos, junto a los datos no SQL

**Comment by SaintChoppa** [comment]
![Image](https://github.com/user-attachments/assets/eb1f14d6-f30b-4a60-b5fe-2665f16e813a)
Modelo SQL actualizado, puede recibir actualizaciones en el futuro pero esta, se creará en MySQL

**Comment by jairoserrano** [comment]
actualizar y reenviar a revisión
