### ISSUE TITLE
Elegir motor de la BD

### ISSUE THREAD

**Issue by SaintChoppa** [ISCOUTB/AH-CineManager#3]

**Comment by ASDRUBALPACHECO** [comment]
el motor de base de datos que vamos a escoger será MySQL.
escogi MySQL porq es una base de datos relacionales en la cual nos va a ayudar demasiado en el proceso de la creacion del programa para poder almacenar los datos de manera mas organizada

**Comment by jairoserrano** [comment]
Seleccionado entonces. procedan a buscar qué imágenes y versiones de docker les funcionará.
